name: minecraft-survival
namespace: minecraft
ip: 192.168.6.162

container:
  image: itzg/minecraft-bedrock-server
  ports:
    - name: minecraft
      port: 19132
      protocol: UDP
  env:
    - name: TZ
      value: "Europe/Amsterdam"
    - name: EULA
      value: "TRUE"
    - name: GAMEMODE
      value: "survival"
    - name: SERVER_NAME
      value: "Fly survival"
    - name: LEVEL_NAME
      value: "Fly survival"
  readinessCommand:
    - mc-monitor
    - status-bedrock
    - --host
    - 127.0.0.1
  resourceRequest:
    cpu: "100m"
    memory: "512Mi"

volumes:
  - name: minecraft-survival
    type: hostPath
    mount: /data
    source: /config/minecraft/survival
