name: adguard
ip: 192.168.6.102

container:
  image: adguard/adguardhome
  ports:
    - name: adguard-http
      port: 80
    - name: adguard-dns-tcp
      port: 53
    - name: adguard-dns-udp
      port: 53
      protocol: udp
  readinessPort: 80

volumes:
  - name: adguard-vol-config
    mount: /opt/adguardhome/conf
  - name: adguard-vol-work
    mount: /opt/adguardhome/work
