name: adguard
ip: 192.168.6.102

container:
  image: adguard/adguardhome
  ports:
    - name: adguard-http
      port: 80
    - name: adguard-dns-tcp
      port: 53
    - name: adguard-dns-udp
      port: 53
      protocol: UDP
  env:
    - name: TZ
      value: "Europe/Amsterdam"
  readinessPort: 80
  resourceRequest:
    cpu: "100m"
    memory: "256Mi"

volumes:
  - name: adguard-vol-config
    type: nfs
    mount: /opt/adguardhome/conf
    source: /config/adguard/conf
  - name: adguard-vol-work
    type: nfs
    mount: /opt/adguardhome/work
    source: /config/adguard/work
