---
apiVersion: v1
kind: Service
metadata:
  name: adguard-svc
  namespace: adguard
  labels:
    name: adguard
    app.kubernetes.io/component: adguard-svc
    app.kubernetes.io/name: adguard
    app.kubernetes.io/part-of: adguard
    app.kubernetes.io/managed-by: argo
spec:
  selector:
    name: adguard
  type: LoadBalancer
  loadBalancerIP: 192.168.6.102
  ports:
    - name: adguard-http
      protocol: TCP
      port: {{ .Values.container.port.http }}
      targetPort: {{ .Values.container.port.http }}
    - name: adguard-dns-tcp
      protocol: TCP
      port: {{ .Values.container.port.dns }}
      targetPort: {{ .Values.container.port.dns }}
    - name: adguard-dns-udp
      protocol: UDP
      port: {{ .Values.container.port.dns }}
      targetPort: {{ .Values.container.port.dns }}
