name: radarr
namespace: media
ip: 192.168.6.122

container:
  image: linuxserver/radarr
  ports:
    - name: http
      port: 7878
  env:
    - name: TZ
      value: "Europe/Amsterdam"
    - name: UMASK
      value: "0022"
  readinessPort: 7878
  resourceRequest:
    cpu: "100m"
    memory: "256Mi"

volumes:
  - name: radarr-config
    type: hostPath
    mount: /config
    source: /config/radarr
  - name: radarr-data
    type: hostPath
    mount: /movies
    source: /data/Movies
  - name: radarr-complete
    type: hostPath
    mount: /downloads
    source: /scratch/complete
