{{- define "common.deployment" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default .Values.name }}
  labels:
    name: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}-app
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/managed-by: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  strategy:
    type: {{ .Values.strategy | default "Recreate" }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.container.image }}:{{ .Values.container.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.container.readinessPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            {{- range $env := .Values.container.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
          ports:
            {{- range $port := .Values.container.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.protocol | default "TCP" }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.container.resourceLimit.cpu | quote }}
              memory: {{ .Values.container.resourceLimit.memory | quote }}
          volumeMounts:
            {{- range $volume := .Values.volumes }}
            - name: {{ $volume.name }}
              mountPath: {{ $volume.mount }}
            {{- end }}
      volumes:
        {{- range $volume := .Values.volumes }}
        - name: {{ $volume.name }}
          persistentVolumeClaim:
            claimName: {{ $volume.name }}
        {{- end }}
{{- end -}}