# Define pvc
{{- define "common.pvc" -}}
# Loop over volumes
{{- range $volume := .Values.volumes }}
# But not when volume is emptyDir
{{ if ne $volume.source "emptyDir" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.name }}
  namespace: {{ $.Values.namespace | default $.Values.name }}
  labels:
    name: {{ $volume.name }}
    app.kubernetes.io/component: {{ $volume.name }}
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/part-of: {{ $.Values.name }}
    app.kubernetes.io/managed-by: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: {{ $volume.name }}
{{- end -}}
{{- end -}}
{{- end -}}
