{{- define "common.service" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace | default .Values.name }}
  labels:
    name: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}-svc
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/managed-by: argo
spec:
  selector:
    name: {{ .Values.name }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.ip }}
  ports:
    {{- range $port := .Values.container.ports }}
    - name: {{ $port.name }}
      protocol: {{ $port.protocol | default "TCP" }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
    {{- end }}
{{- end -}}