name: plex
namespace: media
ip: 192.168.6.130

container:
  image: plexinc/pms-docker
  ports:
    - name: http
      port: 32400
    - name: gdm1
      port: 32410
      protocol: UDP
    - name: gdm2
      port: 32412
      protocol: UDP
    - name: gdm3
      port: 32413
      protocol: UDP
    - name: gdm4
      port: 32414
      protocol: UDP
  env:
    - name: TZ
      value: "Europe/Amsterdam"
    - name: CHANGE_CONFIG_DIR_OWNERSHIP
      value: "false"
  readinessPort: 32400
  resourceRequest:
    cpu: "500m"
    memory: "1024Mi"

volumes:
  - name: plex-config
    type: nfs
    mount: /config
    source: /config/plex
  - name: plex-data
    type: nfs
    mount: /data
    source: /data
  - name: plex-transcode
    type: emptyDir
    mount: /transcode
    source: emptyDir
