---
apiVersion: v1
kind: Service
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/component: metallb-service
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
  loadBalancerIP: 192.168.6.100
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
