apiVersion: v2
appVersion: 4.2.2
description: Helm chart for Sabnzbd
name: sabnzbd
type: application
version: 0.0.1
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../../../helm/common
