name: sabnzbd
namespace: media
ip: 192.168.6.120

container:
  image: linuxserver/sabnzbd
  ports:
    - name: http
      port: 8080
  env:
    - name: TZ
      value: "Europe/Amsterdam"
    - name: UMASK
      value: "0027"
  readinessPort: 8080
  resourceRequest:
    cpu: "1000m"
    memory: "2Gi"

volumes:
  - name: sabnzbd-config
    type: hostPath
    mount: /config
    source: /config/sabnzbd
  - name: sabnzbd-data
    type: hostPath
    mount: /data
    source: /data
  - name: sabnzbd-incomplete
    type: hostPath
    mount: /incomplete-downloads
    source: /scratch/incomplete
  - name: sabnzbd-complete
    type: hostPath
    mount: /downloads
    source: /scratch/complete
