apiVersion: v2
appVersion: 2023.8.1
description: Helm chart for Minecraft Creative
name: minecraft-creative
type: application
version: 0.0.1
dependencies:
  - name: common
    version: 0.0.1
    repository: file://../../../helm/common
