name: sonarr
namespace: media
ip: 192.168.6.121

container:
  image: linuxserver/sonarr
  ports:
    - name: http
      port: 8989
  env:
    - name: TZ
      value: "Europe/Amsterdam"
    - name: UMASK
      value: "0022"
  readinessPort: 8989
  resourceRequest:
    cpu: "100m"
    memory: "256Mi"

volumes:
  - name: sonarr-config
    type: nfs
    mount: /config
    source: /config/sonarr
  - name: sonarr-data
    type: nfs
    mount: /tv
    source: /data/TV
  - name: sonarr-complete
    type: nfs
    mount: /downloads
    source: /scratch/complete
